import axios from "@/api/axiosInstance"

export const listContractCases = (params = {}) => axios.get("/contract-domain/cases", { params }).then(({ data }) => data)
export const listAcceptedCommercialResults = () => axios.get("/contract-domain/accepted-commercial-results").then(({ data }) => data)
export const getContractWorkspace = (caseId) => axios.get(`/contract-domain/cases/${caseId}`).then(({ data }) => data)
export const createContractCase = (payload) => axios.post("/contract-domain/cases/from-accepted-commercial", payload).then(({ data }) => data)
export const createContractRevision = (caseId, payload = {}) => axios.post(`/contract-domain/cases/${caseId}/revisions`, payload).then(({ data }) => data)
export const updateContractRevision = (revisionId, payload) => axios.patch(`/contract-domain/revisions/${revisionId}`, payload).then(({ data }) => data)
export const upsertContractTerm = (revisionId, payload) => axios.put(`/contract-domain/revisions/${revisionId}/terms`, payload).then(({ data }) => data)
export const addContractClause = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/clauses`, payload).then(({ data }) => data)
export const updateContractClause = (clauseId, payload) => axios.patch(`/contract-domain/clauses/${clauseId}`, payload).then(({ data }) => data)
export const analyzeContractImpact = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/analyze-impact`, payload).then(({ data }) => data)
export const requestContractApproval = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/approvals`, payload).then(({ data }) => data)
export const decideContractApproval = (approvalId, payload) => axios.post(`/contract-domain/approvals/${approvalId}/decision`, payload).then(({ data }) => data)
export const getContractReadiness = (revisionId) => axios.get(`/contract-domain/revisions/${revisionId}/readiness`).then(({ data }) => data)
export const getContractPreview = (revisionId) => axios.get(`/contract-domain/revisions/${revisionId}/preview`).then(({ data }) => data)
export const submitContractReview = (revisionId) => axios.post(`/contract-domain/revisions/${revisionId}/submit-review`).then(({ data }) => data)
export const generateContractDocument = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/documents/generate`, payload).then(({ data }) => data)
export const registerContractDocument = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/documents/register`, payload).then(({ data }) => data)
export const sendContractRevision = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/send`, payload).then(({ data }) => data)
export const markContractReadyForSignature = (revisionId) => axios.post(`/contract-domain/revisions/${revisionId}/ready-for-signature`).then(({ data }) => data)
export const registerContractSignature = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/signatures`, payload).then(({ data }) => data)
export const makeContractEffective = (revisionId, payload) => axios.post(`/contract-domain/revisions/${revisionId}/make-effective`, payload).then(({ data }) => data)
export const listContractCommitments = (caseId) => axios.get(`/contract-domain/cases/${caseId}/commitments`).then(({ data }) => data)
export const compareContractRevisions = (caseId, fromId, toId) => axios.get(`/contract-domain/cases/${caseId}/revisions/${fromId}/compare/${toId}`).then(({ data }) => data)
