import axios from '@/api/axiosInstance'
export const getAfterSalesOverview=params=>axios.get('/after-sales/overview',{params}).then(({data})=>data)
export const getEligibleDeliveries=params=>axios.get('/after-sales/eligible-deliveries',{params}).then(({data})=>data)
export const getAfterSalesCase=id=>axios.get(`/after-sales/cases/${id}`).then(({data})=>data)
export const getAfterSalesHistory=params=>axios.get('/after-sales/history',{params}).then(({data})=>data)
export const createAfterSalesCase=payload=>axios.post('/after-sales/cases',payload).then(({data})=>data)
export const transitionAfterSalesCase=(id,payload)=>axios.post(`/after-sales/cases/${id}/transitions`,payload).then(({data})=>data)
export const addAfterSalesEvidence=(id,payload)=>axios.post(`/after-sales/cases/${id}/evidence`,payload).then(({data})=>data)
export const addAfterSalesInvestigation=(id,payload)=>axios.post(`/after-sales/cases/${id}/investigation`,payload).then(({data})=>data)
export const proposeAfterSalesResolution=(id,payload)=>axios.post(`/after-sales/cases/${id}/resolutions`,payload).then(({data})=>data)
export const resolveAfterSalesCase=(id,payload)=>axios.post(`/after-sales/cases/${id}/resolve`,payload).then(({data})=>data)
export const createSupplierEscalation=(id,payload)=>axios.post(`/after-sales/cases/${id}/supplier-escalations`,payload).then(({data})=>data)
export const createDownstreamHandoff=(id,payload)=>axios.post(`/after-sales/cases/${id}/downstream-handoffs`,payload).then(({data})=>data)
export const closeAfterSalesCase=(id,payload)=>axios.post(`/after-sales/cases/${id}/close`,payload).then(({data})=>data)
export const reopenAfterSalesCase=(id,payload)=>axios.post(`/after-sales/cases/${id}/reopen`,payload).then(({data})=>data)
