steps:
  # 1. Установить зависимости
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # 2. Собрать фронтенд
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 3. Загрузить содержимое dist/ в Cloud Storage bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gsutil',
        '-m',
        'cp',
        '-r',
        'dist/*',
        'gs://crusher-parts-frontend-site',
      ]
