import axios from "@/api/axiosInstance"

export const listCommercialOffers = (params = {}) => axios.get("/commercial-offers/offers", { params }).then(({ data }) => data)
export const listCommercialOfferPricingDecisions = () => axios.get("/commercial-offers/pricing-decisions").then(({ data }) => data)
export const getCommercialOfferWorkspace = (offerId) => axios.get(`/commercial-offers/offers/${offerId}`).then(({ data }) => data)
export const createCommercialOffer = (payload) => axios.post("/commercial-offers/offers/from-pricing-decision", payload).then(({ data }) => data)
export const createCommercialOfferRevisionFromPricingDecision = (offerId, payload) => axios.post(`/commercial-offers/offers/${offerId}/revisions/from-pricing-decision`, payload).then(({ data }) => data)
export const updateCommercialOfferRevision = (revisionId, payload) => axios.patch(`/commercial-offers/revisions/${revisionId}`, payload).then(({ data }) => data)
export const updateCommercialOfferLine = (lineId, payload) => axios.patch(`/commercial-offers/lines/${lineId}`, payload).then(({ data }) => data)
export const getCommercialOfferReadiness = (revisionId) => axios.get(`/commercial-offers/revisions/${revisionId}/readiness`).then(({ data }) => data)
export const getCommercialOfferClientPreview = (revisionId) => axios.get(`/commercial-offers/revisions/${revisionId}/client-preview`).then(({ data }) => data)
export const submitCommercialOfferReview = (revisionId) => axios.post(`/commercial-offers/revisions/${revisionId}/submit-review`).then(({ data }) => data)
export const requestCommercialApproval = (revisionId, payload) => axios.post(`/commercial-offers/revisions/${revisionId}/approvals`, payload).then(({ data }) => data)
export const decideCommercialApproval = (approvalId, payload) => axios.post(`/commercial-offers/approvals/${approvalId}/decision`, payload).then(({ data }) => data)
export const markCommercialOfferReady = (revisionId) => axios.post(`/commercial-offers/revisions/${revisionId}/ready`).then(({ data }) => data)
export const renderCommercialOffer = (revisionId) => axios.post(`/commercial-offers/revisions/${revisionId}/render`).then(({ data }) => data)
export const sendCommercialOffer = (revisionId, payload) => axios.post(`/commercial-offers/revisions/${revisionId}/send`, payload).then(({ data }) => data)
export const registerCommercialFeedback = (offerId, payload) => axios.post(`/commercial-offers/offers/${offerId}/feedback`, payload).then(({ data }) => data)
export const assessCommercialFeedback = (feedbackId) => axios.post(`/commercial-offers/feedback/${feedbackId}/assess-impact`).then(({ data }) => data)
export const createCommercialOfferNextRevision = (feedbackId, payload = {}) => axios.post(`/commercial-offers/feedback/${feedbackId}/create-next-revision`, payload).then(({ data }) => data)
export const acceptCommercialOffer = (offerId, payload) => axios.post(`/commercial-offers/offers/${offerId}/acceptance`, payload).then(({ data }) => data)
export const getAcceptedCommercialResult = (offerId) => axios.get(`/commercial-offers/offers/${offerId}/accepted-result`).then(({ data }) => data)
export const compareCommercialOfferRevisions = (offerId, fromId, toId) => axios.get(`/commercial-offers/offers/${offerId}/revisions/${fromId}/compare/${toId}`).then(({ data }) => data)
