import React,{useCallback,useEffect,useMemo,useState} from 'react'
import {App,Button,Card,Col,Descriptions,Empty,Form,Input,Modal,Row,Select,Space,Statistic,Table,Tabs,Tag,Typography} from 'antd'
import {CheckCircleOutlined,HistoryOutlined,ReloadOutlined} from '@ant-design/icons'
import useCapabilities from '@/hooks/useCapabilities'
import {closeCompletionCase,evaluateCompletionCase,getCompletionCase,getCompletionOverview,materializeCompletionCase,reopenCompletionCase} from '@/features/completionLifecycle/api/completionLifecycleApi'
const {Paragraph,Text,Title}=Typography
const stateColor={ACTIVE:'blue',NOT_READY:'red',READY_TO_CLOSE:'green',CLOSED:'default',REOPENED:'gold',SATISFIED:'green',BLOCKED:'red'}
const stateLabel={ACTIVE:'Активно',NOT_READY:'Не готово',READY_TO_CLOSE:'Готово к завершению',CLOSED:'Завершено',REOPENED:'Открыто повторно',SATISFIED:'Выполнено',BLOCKED:'Заблокировано',NOT_EVALUATED:'Не проверено'}
const Status=({value})=><Tag color={stateColor[value]||'default'}>{stateLabel[value]||'Неизвестное состояние'}</Tag>
const gateLabel={CONTRACT:'Договор',PROCUREMENT:'Закупка',WAREHOUSE:'Склад',DISPATCH:'Доставка',FINANCE:'Финансы',AFTER_SALES:'Рекламации'}

export default function CompletionLifecycleWorkspacePage(){
 const {message}=App.useApp(),{can}=useCapabilities(),[data,setData]=useState({active_cases:[],closed_cases:[]}),[loading,setLoading]=useState(false),[contractSource,setContractSource]=useState(null),[detail,setDetail]=useState(null),[closing,setClosing]=useState(null),[reopening,setReopening]=useState(null),[closeForm]=Form.useForm(),[reopenForm]=Form.useForm()
 const load=useCallback(async()=>{setLoading(true);try{setData(await getCompletionOverview())}catch(error){message.error(error?.response?.data?.message||'Не удалось загрузить Completion & Lifecycle')}finally{setLoading(false)}},[message])
 useEffect(()=>{load()},[load])
 const inspect=async row=>{try{setDetail(await getCompletionCase(row.id))}catch(error){message.error(error?.response?.data?.message||'Case не загружен')}}
 const materialize=async()=>{if(!contractSource)return;try{await materializeCompletionCase(contractSource);message.success('Заказ добавлен в очередь завершения');setContractSource(null);load()}catch(error){message.error(error?.response?.data?.message||'Заказ не добавлен')}}
 const evaluate=async row=>{try{const result=await evaluateCompletionCase(row.id);message.success(result.state==='READY_TO_CLOSE'?'Case READY_TO_CLOSE':'Readiness записан: NOT_READY');await load();await inspect(row)}catch(error){message.error(error?.response?.data?.message||'Evaluation не выполнен')}}
 const openClose=row=>{setClosing(row);closeForm.setFieldsValue({closure_evidence_reference:'manual-closure-approval',idempotency_key:`completion-close-${row.id}-${Date.now()}`})}
 const close=async()=>{try{await closeCompletionCase(closing.id,{...(await closeForm.validateFields()),row_version:closing.row_version});message.success('CaseClosed: immutable Completion Snapshot создан');setClosing(null);load()}catch(error){if(!error?.errorFields)message.error(error?.response?.data?.message||'Case не закрыт')}}
 const openReopen=row=>{setReopening(row);reopenForm.setFieldsValue({idempotency_key:`completion-reopen-${row.id}-${Date.now()}`})}
 const reopen=async()=>{try{await reopenCompletionCase(reopening.id,{...(await reopenForm.validateFields()),row_version:reopening.row_version});message.success('Exceptional reopen записан; прежний snapshot сохранён');setReopening(null);load()}catch(error){if(!error?.errorFields)message.error(error?.response?.data?.message||'Case не переоткрыт')}}
 const columns=useMemo(()=>[{title:'Заказ',render:(_,r)=><Space direction="vertical" size={0}><Text strong>{r.case_number}</Text><Text type="secondary">{r.contract_number} · {r.company_name}</Text></Space>},{title:'Жизненный цикл',dataIndex:'lifecycle_state',render:v=><Status value={v}/>},{title:'Готовность',dataIndex:'last_readiness_state',render:v=><Status value={v||'NOT_EVALUATED'}/>},{title:'Причины блокировки',render:(_,r)=>(r.last_blockers_json||[]).length?<Tag color="red">Есть невыполненные условия</Tag>:'—'},{title:'Правила завершения',render:(_,r)=>`Версия ${r.policy_revision_number}`},{title:'Действия',render:(_,r)=><Space wrap><Button size="small" onClick={()=>inspect(r)}>Подробнее</Button>{r.lifecycle_state!=='CLOSED'&&can('completion.readiness.evaluate')&&<Button size="small" onClick={()=>evaluate(r)}>Проверить</Button>}{r.lifecycle_state!=='CLOSED'&&can('completion.close')&&<Button size="small" type="primary" icon={<CheckCircleOutlined/>} onClick={()=>openClose(r)}>Завершить</Button>}{r.lifecycle_state==='CLOSED'&&can('completion.reopen')&&<Button size="small" danger icon={<HistoryOutlined/>} onClick={()=>openReopen(r)}>Открыть повторно</Button>}</Space>}],[can])
 const active=data.active_cases||[],closed=data.closed_cases||[],ready=active.filter(x=>x.lifecycle_state==='READY_TO_CLOSE'||x.last_readiness_state==='READY_TO_CLOSE')
 const table=rows=><Table rowKey="id" loading={loading} columns={columns} dataSource={rows} locale={{emptyText:<Empty description="Заказы отсутствуют"/>}}/>
 return <Space direction="vertical" size="large" style={{width:'100%'}}>
  <Row justify="space-between" align="middle"><Col><Title level={3} style={{margin:0}}>Завершение заказа</Title><Text type="secondary">Проверка исполнения → явное завершение → зафиксированный итог → исключительное повторное открытие</Text></Col><Col><Button icon={<ReloadOutlined/>} onClick={load} loading={loading}>Обновить</Button></Col></Row>
  {can('completion.readiness.evaluate')&&<Card size="small" title="Добавить действующий договор в проверку завершения"><Space><Select value={contractSource} onChange={setContractSource} placeholder="Выберите договор" style={{width:480}} options={(data.contract_intake||[]).map(item=>({value:item.id,disabled:Boolean(item.completion_case_id),label:`${item.contract_number} · ${item.company_name}${item.case_number?` · уже ${item.case_number}`:''}`}))}/><Button type="primary" disabled={!contractSource} onClick={materialize}>Добавить</Button></Space></Card>}
  <Row gutter={16}>{[['Активные / не готовы',active.length-ready.length],['Готовы к завершению',ready.length],['Завершены',closed.length],['Открыты повторно',active.filter(x=>x.lifecycle_state==='REOPENED').length]].map(([title,value])=><Col xs={12} lg={6} key={title}><Card><Statistic title={title} value={value}/></Card></Col>)}</Row>
  <Tabs items={[{key:'active',label:'Активные / не готовы',children:table(active.filter(x=>!ready.includes(x)))},{key:'ready',label:'Готовы к завершению',children:table(ready)},{key:'closed',label:'Завершённые / история',children:table(closed)},{key:'policy',label:'Правила завершения',children:<Card><Space direction="vertical"><Text>Перед завершением система проверяет поставку, финансовые обязательства и отсутствие блокирующих исключений.</Text><Text>Подтверждение доставки (POD) обязательно: одного факта отправки недостаточно.</Text><Text>Завершение запускается только явным действием пользователя.</Text><Text>Повторное открытие требует причины и подтверждения; прежний итог не изменяется.</Text></Space></Card>}]} />
  <Modal width={900} title="Проверка готовности к завершению" open={Boolean(detail)} onCancel={()=>setDetail(null)} footer={null}>{detail&&<Space direction="vertical" style={{width:'100%'}}><Descriptions bordered size="small" column={2} items={[{key:'case',label:'Заказ',children:detail.case.case_number},{key:'state',label:'Жизненный цикл',children:<Status value={detail.case.lifecycle_state}/>},{key:'policy',label:'Правила',children:`Версия ${detail.case.policy_revision_number}`},{key:'contract',label:'Договор',children:detail.case.contract_number}]} />{detail.current_readiness&&<Card title="Текущая готовность"><Space direction="vertical" style={{width:'100%'}}><Status value={detail.current_readiness.state}/>{detail.current_readiness.gates.map(g=><Row key={g.gate_code} justify="space-between"><Col><Text>{gateLabel[g.gate_code]||'Условие завершения'}</Text></Col><Col><Status value={g.status}/></Col></Row>)}</Space></Card>}<Card title="Что мешает завершению">{detail.current_readiness?.blockers?.length?<Space direction="vertical">{detail.current_readiness.blockers.map((x,i)=><Text key={i}>• {gateLabel[x.gate]||'Обязательное условие'}: требуется завершить связанные операции</Text>)}</Space>:<Empty description="Блокирующие условия отсутствуют"/>}</Card><Card title="Зафиксированные завершения"><Table rowKey="id" size="small" dataSource={detail.snapshots} columns={[{title:'Номер',dataIndex:'closure_sequence'},{title:'Дата завершения',dataIndex:'closed_at'},{title:'Связанных записей',dataIndex:'traceability_snapshot_json',render:v=>Array.isArray(v)?v.length:0}]}/></Card><Card title="История жизненного цикла"><Table rowKey="id" size="small" dataSource={detail.lifecycle_history} columns={[{title:'Событие',dataIndex:'event_type'},{title:'Версия',dataIndex:'lifecycle_revision_number'},{title:'Причина',dataIndex:'reason_code'},{title:'Пояснение',dataIndex:'explanation'},{title:'Подтверждение',dataIndex:'evidence_reference'},{title:'Дата',dataIndex:'occurred_at'}]}/></Card></Space>}</Modal>
  <Modal title="Завершить заказ" open={Boolean(closing)} onCancel={()=>setClosing(null)} onOk={close}><Form form={closeForm} layout="vertical"><Form.Item name="closure_evidence_reference" label="Основание для завершения" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="idempotency_key" hidden><Input/></Form.Item><Text type="secondary">Перед завершением система ещё раз проверит все обязательные условия.</Text></Form></Modal>
  <Modal title="Открыть заказ повторно" open={Boolean(reopening)} onCancel={()=>setReopening(null)} onOk={reopen} okText="Открыть повторно" cancelText="Отмена"><Form form={reopenForm} layout="vertical"><Form.Item name="reason_code" label="Причина" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="explanation" label="Пояснение" rules={[{required:true}]}><Input.TextArea rows={3}/></Form.Item><Form.Item name="evidence_reference" label="Подтверждение полномочий" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="idempotency_key" hidden><Input/></Form.Item><Text type="secondary">Прежний зафиксированный итог не изменится; система добавит новую запись жизненного цикла.</Text></Form></Modal>
 </Space>
}
