import React,{useCallback,useEffect,useMemo,useState} from 'react'
import {App,Button,Card,Col,Empty,Form,Input,InputNumber,Modal,Row,Space,Statistic,Table,Tabs,Tag,Typography} from 'antd'
import {ReloadOutlined,SendOutlined} from '@ant-design/icons'
import axios from '@/api/axiosInstance'
import useCapabilities from '@/hooks/useCapabilities'
import {confirmDelivery,confirmPicking,createDispatchOrder,createPackage,createShipment,dispatchShipment,getDispatchOrder,getDispatchOverview,packPackage,requestPicking} from '@/features/dispatchDelivery/api/dispatchDeliveryApi'
const {Text,Title}=Typography
const number=v=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:3})
const colors={PLANNING:'default',READY:'green',READY_TO_SHIP:'green',PICKING:'blue',PACKING:'cyan',PACKED:'blue',ASSIGNED:'purple',DISPATCHED:'geekblue',PARTIALLY_DISPATCHED:'gold',PARTIALLY_DELIVERED:'gold',DELIVERED:'green',COMPLETED:'green',OPEN:'red',BLOCKED:'red'}
const labels={PLANNING:'Планирование',READY:'Готово',READY_TO_SHIP:'Готово к отгрузке',ALLOCATED:'Зарезервировано',PICKED:'Скомплектовано',PICKING:'Комплектация',PACKING:'Упаковка',PACKED:'Упаковано',ASSIGNED:'Назначено',DISPATCHED:'Отправлено',PARTIALLY_DISPATCHED:'Отправлено частично',PARTIALLY_DELIVERED:'Доставлено частично',DELIVERED:'Доставлено',COMPLETED:'Завершено',OPEN:'Открыто',BLOCKED:'Заблокировано',FULFILLED:'Выполнено',PARTIALLY_FULFILLED:'Выполнено частично',NOT_FULFILLED:'Не выполнено',NOT_STARTED:'Не начато'}
const Status=({value})=><Tag color={colors[value]||'default'}>{labels[value]||'Неизвестное состояние'}</Tag>

export default function DispatchDeliveryWorkspacePage(){
 const {message}=App.useApp(),{can}=useCapabilities(),[data,setData]=useState({}),[loading,setLoading]=useState(false),[orderSource,setOrderSource]=useState(null),[shipmentPackage,setShipmentPackage]=useState(null),[podSource,setPodSource]=useState(null),[orderForm]=Form.useForm(),[shipmentForm]=Form.useForm(),[podForm]=Form.useForm()
 const load=useCallback(async()=>{setLoading(true);try{setData(await getDispatchOverview())}catch(error){message.error(error?.response?.data?.message||'Не удалось загрузить Dispatch & Delivery')}finally{setLoading(false)}},[message])
 useEffect(()=>{load()},[load])
 const orders=data.dispatch_orders||[],shipments=data.shipments||[],ready=data.ready_to_dispatch||[]
 const openOrder=row=>{setOrderSource(row);orderForm.setFieldsValue({quantity:Number(row.remaining_to_allocate),idempotency_key:`dispatch-order-${row.contract_commitment_id}-${Date.now()}`})}
 const submitOrder=async()=>{try{const v=await orderForm.validateFields();await createDispatchOrder({idempotency_key:v.idempotency_key,allocations:[{contract_commitment_id:orderSource.contract_commitment_id,quantity:v.quantity}]});message.success('Заказ на отгрузку создан');setOrderSource(null);load()}catch(error){if(!error?.errorFields)message.error(error?.response?.data?.message||'Заказ на отгрузку не создан')}}
 const preparePicking=async row=>{try{const [details,{data:warehouse}]=await Promise.all([getDispatchOrder(row.id),axios.get('/warehouse-inventory/overview')]),allocation=details.allocations?.[0],stock=(warehouse.stock||[]).find(item=>Number(item.catalog_position_id)===Number(allocation?.catalog_position_id)&&Number(item.available_quantity)+0.0005>=Number(allocation?.allocated_quantity));if(!allocation||!stock)throw new Error('Нет подходящего доступного складского лота');const reservation=(await axios.post('/warehouse-inventory/reservations/with-allocations',{source_domain:'dispatch_delivery',source_entity_type:'dispatch_order',source_entity_id:row.id,source_revision_id:row.row_version,evidence:{reason:'Комплектация заказа на отгрузку',order_number:row.order_number},idempotency_key:`dispatch-reservation-${row.id}`,allocations:[{stock_unit_id:stock.stock_unit_id,quantity:Number(allocation.allocated_quantity)}]})).data;await requestPicking(row.id,{warehouse_id:stock.warehouse_id,idempotency_key:`dispatch-picking-${row.id}`,lines:[{dispatch_order_allocation_id:allocation.id,warehouse_reservation_allocation_id:reservation.allocations[0].id,quantity:Number(allocation.allocated_quantity)}]});message.success('Товар зарезервирован и передан на комплектацию');load()}catch(error){message.error(error?.response?.data?.message||error.message||'Не удалось начать комплектацию')}}
 const finishPicking=async row=>{try{await confirmPicking(row.id,{row_version:row.row_version,evidence_reference:`Комплектация подтверждена пользователем · ${row.request_number}`});message.success('Комплектация подтверждена');load()}catch(error){message.error(error?.response?.data?.message||'Комплектация не подтверждена')}}
 const makePackage=async row=>{try{const details=await getDispatchOrder(row.dispatch_order_id),line=(details.picking_lines||[]).find(item=>Number(item.dispatch_picking_request_id)===Number(row.id)&&item.status==='PICKED');if(!line)throw new Error('Не найдена скомплектованная позиция');const created=await createPackage({dispatch_order_id:row.dispatch_order_id,package_type:'Короб',idempotency_key:`dispatch-package-${row.dispatch_order_id}`,contents:[{picking_request_line_id:line.id,quantity:Number(line.picked_quantity)}]});await packPackage(created.package_id,{row_version:1});message.success('Упаковка создана и закрыта');load()}catch(error){message.error(error?.response?.data?.message||error.message||'Упаковка не создана')}}
 const openShipment=row=>{setShipmentPackage(row);shipmentForm.setFieldsValue({carrier_name:'E2E86 Test Carrier',tracking_number:`E2E86-${Date.now()}`})}
 const submitShipment=async()=>{try{const v=await shipmentForm.validateFields();await createShipment({package_ids:[shipmentPackage.id],carrier:{name:v.carrier_name,available:true},tracking:{number:v.tracking_number,available:true},terms:{mode:'Доставка клиенту'},reason:'Создано пользователем',idempotency_key:`shipment-package-${shipmentPackage.id}`});message.success('Отправление создано');setShipmentPackage(null);load()}catch(error){if(!error?.errorFields)message.error(error?.response?.data?.message||'Отправление не создано')}}
 const submitDispatch=async row=>{try{await dispatchShipment(row.id,{row_version:row.row_version,idempotency_key:`shipment-dispatch-${row.id}`});message.success('Отправление передано перевозчику, складской остаток списан');load()}catch(error){message.error(error?.response?.data?.message||'Отправление не передано перевозчику')}}
 const openPod=row=>{setPodSource(row);podForm.setFieldsValue({delivered_at:new Date().toISOString(),delivered_quantity:Number(row.dispatched_quantity)-Number(row.delivered_quantity),dispatch_order_allocation_id:Number(String(row.allocation_ids||'').split(',')[0]),idempotency_key:`pod-${row.id}-${Date.now()}`})}
 const submitPod=async()=>{try{const v=await podForm.validateFields();await confirmDelivery(podSource.id,{...v,lines:[{dispatch_order_allocation_id:v.dispatch_order_allocation_id,delivered_quantity:v.delivered_quantity}]});message.success('POD зарегистрирован');setPodSource(null);load()}catch(error){if(!error?.errorFields)message.error(error?.response?.data?.message||'POD не зарегистрирован')}}
 const blockerLabel={DESTINATION_SNAPSHOT_REQUIRED:'Не указан адрес доставки',CATALOG_POSITION_UNRESOLVED:'Не определена позиция каталога',WAREHOUSE_STOCK_NOT_AVAILABLE:'Недостаточно складского остатка'}
 const readyColumns=useMemo(()=>[{title:'Обязательство договора',render:(_,r)=><Space direction="vertical" size={0}><Text strong>{r.contract_number} · строка {r.line_number}</Text><Text type="secondary">{r.client_name}</Text></Space>},{title:'Требуется',render:(_,r)=>`${number(r.required_quantity)} ${r.uom==='UNSPECIFIED'?'шт':r.uom}`},{title:'Распределено',dataIndex:'allocated_quantity',render:number},{title:'Доставлено',dataIndex:'delivered_quantity',render:number},{title:'Исполнение',dataIndex:'fulfillment_projection',render:v=><Status value={v}/>},{title:'Готовность',render:(_,r)=>r.dispatch_ready?<Tag color="green">Готово</Tag>:<Space wrap>{(r.blockers||[]).map(x=><Tag key={x} color="red">{blockerLabel[x]||'Требуется проверка'}</Tag>)}</Space>},{title:'',render:(_,r)=>can('dispatch_delivery.orders.manage')&&r.dispatch_ready?<Button size="small" onClick={()=>openOrder(r)}>Создать заказ на отгрузку</Button>:null}], [can])
 const orderColumns=[{title:'Заказ на отгрузку',render:(_,r)=><Space direction="vertical" size={0}><Text strong>{r.order_number}</Text><Text type="secondary">{r.client_name}</Text></Space>},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Позиций',dataIndex:'allocation_count'},{title:'Распределено',dataIndex:'allocated_quantity',render:number},{title:'Доставлено',dataIndex:'delivered_quantity',render:number},{title:'Действие',render:(_,r)=>r.status==='PLANNING'&&can('dispatch_delivery.picking.manage')?<Button size="small" onClick={()=>preparePicking(r)}>Передать на комплектацию</Button>:null}]
 const shipmentColumns=[{title:'Отправление',dataIndex:'shipment_number',render:v=><Text strong>{v}</Text>},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Упаковок',dataIndex:'package_count'},{title:'Заказов',dataIndex:'order_count'},{title:'Отправлено',dataIndex:'dispatched_quantity',render:number},{title:'Доставлено',dataIndex:'delivered_quantity',render:number},{title:'Перевозчик / отслеживание',render:(_,r)=><Space direction="vertical" size={0}><Text>{r.carrier_snapshot_json?.name||r.carrier_snapshot_json?.reference||'—'}</Text><Text type="secondary">{r.tracking_snapshot_json?.number||r.tracking_snapshot_json?.reference||'—'}</Text></Space>},{title:'Действия',render:(_,r)=><Space>{can('dispatch_delivery.shipments.dispatch')&&r.status==='READY'&&<Button size="small" icon={<SendOutlined/>} onClick={()=>submitDispatch(r)}>Передать перевозчику</Button>}{can('dispatch_delivery.delivery.confirm')&&['DISPATCHED','IN_TRANSIT','PARTIALLY_DELIVERED'].includes(r.status)&&<Button size="small" onClick={()=>openPod(r)}>Подтвердить доставку</Button>}</Space>}]
 const simple=(columns,rows,key='id')=><Table rowKey={key} loading={loading} columns={columns} dataSource={rows} locale={{emptyText:<Empty description="Данные пока отсутствуют"/>}}/>
 return <Space direction="vertical" size="large" style={{width:'100%'}}>
  <Row justify="space-between" align="middle"><Col><Title level={3} style={{margin:0}}>Отгрузка и доставка</Title><Text type="secondary">Потребность договора → комплектация → упаковка → отправка → подтверждение доставки (POD)</Text></Col><Col><Button icon={<ReloadOutlined/>} loading={loading} onClick={load}>Обновить</Button></Col></Row>
  <Row gutter={16}>{[['Готово',ready.filter(x=>x.dispatch_ready).length],['Заказы на отгрузку',orders.length],['Отправления',shipments.length],['Подтверждения доставки',(data.delivery_confirmations||[]).length]].map(([t,v])=><Col xs={12} lg={6} key={t}><Card><Statistic title={t} value={v}/></Card></Col>)}</Row>
  <Tabs items={[
   {key:'ready',label:'Готово к отгрузке',children:simple(readyColumns,ready,'contract_commitment_id')},
   {key:'orders',label:'Заказы на отгрузку',children:simple(orderColumns,orders)},
   {key:'picking',label:'Комплектация',children:simple([{title:'Задание',dataIndex:'request_number'},{title:'Заказ',dataIndex:'order_number'},{title:'Склад',dataIndex:'warehouse_name'},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Позиций',dataIndex:'line_count'},{title:'Подтверждение',dataIndex:'evidence_reference'},{title:'Действие',render:(_,r)=>r.status==='ALLOCATED'?<Button size="small" onClick={()=>finishPicking(r)}>Подтвердить комплектацию</Button>:r.status==='PICKED'&&!orders.find(o=>Number(o.id)===Number(r.dispatch_order_id))?.package_count?<Button size="small" onClick={()=>makePackage(r)}>Создать упаковку</Button>:null}],data.picking||[])},
   {key:'packages',label:'Упаковки',children:simple([{title:'Упаковка',dataIndex:'package_number'},{title:'Заказ',dataIndex:'order_number'},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Позиций',dataIndex:'content_count'},{title:'Количество',dataIndex:'content_quantity',render:number},{title:'Действие',render:(_,r)=>r.status==='PACKED'?<Button size="small" onClick={()=>openShipment(r)}>Создать отправление</Button>:null}],data.packages||[])},
   {key:'shipments',label:'Отправления',children:simple(shipmentColumns,shipments)},
   {key:'delivery',label:'Подтверждения доставки',children:simple([{title:'POD',dataIndex:'confirmation_number'},{title:'Отправление',dataIndex:'shipment_number'},{title:'Доставлено',dataIndex:'delivered_at'},{title:'Получил',dataIndex:'received_by'},{title:'Количество',dataIndex:'delivered_quantity',render:number},{title:'Подтверждение',dataIndex:'evidence_reference'}],data.delivery_confirmations||[])},
   {key:'exceptions',label:'Исключения',children:simple([{title:'Тип',dataIndex:'exception_type'},{title:'Серьёзность',dataIndex:'severity',render:v=><Tag color={v==='CRITICAL'?'red':'orange'}>{v==='CRITICAL'?'Критическая':'Требует внимания'}</Tag>},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Подтверждение',dataIndex:'evidence_reference'}],data.exceptions||[])},
   {key:'history',label:'Правила раздела',children:<Card><Space direction="vertical"><Text>Договор и его обязательства доступны только для чтения.</Text><Text>Физический, зарезервированный и доступный остаток принадлежат складу; списание выполняется только при передаче перевозчику.</Text><Text>Раздел управляет заказами на отгрузку, комплектацией, упаковками, отправлениями и подтверждениями доставки.</Text><Text>Передача перевозчику ещё не означает исполнение. Исполнение подтверждается только фактически доставленным количеством.</Text><Text>Финансы, закупка и расчёт цены здесь не изменяются.</Text></Space></Card>},
  ]}/>
  <Modal title="Создать заказ на отгрузку" open={Boolean(orderSource)} onCancel={()=>setOrderSource(null)} onOk={submitOrder} okText="Создать" cancelText="Отмена"><Form form={orderForm} layout="vertical"><Form.Item label="Договор"><Input value={orderSource?`${orderSource.contract_number} · ${orderSource.client_name}`:''} disabled/></Form.Item><Form.Item name="quantity" label="Количество" rules={[{required:true}]}><InputNumber min={0.001} style={{width:'100%'}}/></Form.Item><Form.Item name="idempotency_key" hidden><Input/></Form.Item></Form></Modal>
  <Modal title="Создать отправление" open={Boolean(shipmentPackage)} onCancel={()=>setShipmentPackage(null)} onOk={submitShipment} okText="Создать" cancelText="Отмена"><Form form={shipmentForm} layout="vertical"><Form.Item name="carrier_name" label="Перевозчик" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="tracking_number" label="Номер отслеживания" rules={[{required:true}]}><Input/></Form.Item></Form></Modal>
  <Modal title="Подтвердить доставку" open={Boolean(podSource)} onCancel={()=>setPodSource(null)} onOk={submitPod} okText="Подтвердить" cancelText="Отмена"><Form form={podForm} layout="vertical"><Form.Item name="delivered_at" label="Дата и время доставки" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="received_by" label="Получатель" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="evidence_reference" label="Документ или подтверждение доставки" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="delivered_quantity" label="Доставленное количество" rules={[{required:true}]}><InputNumber min={0.001} style={{width:'100%'}}/></Form.Item><Form.Item name="dispatch_order_allocation_id" hidden><InputNumber/></Form.Item><Form.Item name="idempotency_key" hidden><Input/></Form.Item></Form></Modal>
 </Space>
}
