import React,{useCallback,useEffect,useMemo,useState} from 'react'
import {Alert,Button,Card,Col,Descriptions,Drawer,Form,Input,InputNumber,Row,Select,Space,Statistic,Table,Tabs,Tag,Typography} from 'antd'
import PageWrapper from '@/components/common/PageWrapper'
import useCapabilities from '@/hooks/useCapabilities'
import {appMessage} from '@/utils/uiFeedback'
import {createPaymentPlan,getCompletionReadiness,getFinancialWorkspace,materializeAp,materializeReceivable,openFinancialDispute,registerCreditNote,registerCustomerCreditAdjustment,registerCustomerPayment,registerSupplierInvoice,registerSupplierPayment} from '@/features/financialOperations/api/financialOperationsApi'

const {Text,Title}=Typography
const errorText=(reason)=>reason?.response?.data?.error?.message||reason?.response?.data?.message||reason?.message||'Операция не выполнена'
const money=(value,currency)=>value==null?'—':`${Number(value).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:4})} ${currency||''}`
const key=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`
const statusColor={ACTIVE:'blue',PAID:'green',ALLOCATED:'green',OPEN:'blue',OVERDUE:'red',DISPUTED:'red',BLOCKED:'red',PLANNED:'gold',PARTIALLY_PAID:'orange',PARTIALLY_INVOICED:'orange',PARTIALLY_ALLOCATED:'orange',WAITING_FOR_TRIGGER:'default'}
const statusLabel={ACTIVE:'Активно',PAID:'Оплачено',ALLOCATED:'Распределено',OPEN:'Открыто',OVERDUE:'Просрочено',DISPUTED:'Оспаривается',BLOCKED:'Заблокировано',PLANNED:'Запланировано',PARTIALLY_PAID:'Оплачено частично',PARTIALLY_INVOICED:'Выставлено частично',PARTIALLY_ALLOCATED:'Распределено частично',WAITING_FOR_TRIGGER:'Ожидается условие'}
const Status=({value})=><Tag color={statusColor[value]}>{statusLabel[value]||'Неизвестное состояние'}</Tag>
const allocationKeys=(rows,type)=>(rows||[]).map((item,index)=>({...item,idempotency_key:key(`${type}-${index}`)}))

export default function FinancialOperationsWorkspacePage(){
  const {can}=useCapabilities(),[model,setModel]=useState(null),[loading,setLoading]=useState(true),[drawer,setDrawer]=useState(null),[completion,setCompletion]=useState(null)
  const [form]=Form.useForm()
  const load=useCallback(async()=>{setLoading(true);try{setModel(await getFinancialWorkspace())}catch(reason){appMessage.error(errorText(reason))}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const run=async(operation,success)=>{try{await operation();appMessage.success(success);setDrawer(null);form.resetFields();await load()}catch(reason){appMessage.error(errorText(reason))}}
  const open=(name,defaults={})=>{form.resetFields();form.setFieldsValue(defaults);setDrawer(name)}
  const generic=[{title:'Номер',render:(_,r)=>r.case_number||r.external_invoice_number||r.payment_number||r.receivable_number||`Запись ${r.id}`},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Сумма',render:(_,r)=>money(r.total_amount||r.expected_amount||r.gross_amount||r.amount,r.currency)}]
  const commitments=[{title:'Основание',dataIndex:'case_number'},{title:'Поставщик',dataIndex:'supplier_name'},{title:'К оплате',render:(_,r)=>money(r.expected_amount,r.currency)},{title:'По счетам',render:(_,r)=>money(r.invoiced_amount,r.currency)},{title:'Оплачено',render:(_,r)=>money(r.paid_amount,r.currency)},{title:'Срок',dataIndex:'contractual_due_date'},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>}]
  const receivables=[{title:'Задолженность',dataIndex:'receivable_number'},{title:'Клиент',dataIndex:'client_name'},{title:'Ожидается',render:(_,r)=>money(r.expected_amount,r.currency)},{title:'Получено',render:(_,r)=>money(r.received_amount,r.currency)},{title:'Срок',dataIndex:'due_date',render:v=>v||<Text type="warning">не указан</Text>},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>}]
  const history=[{title:'Когда',dataIndex:'occurred_at'},{title:'Событие',dataIndex:'event_type'},{title:'Объект',render:(_,r)=>r.aggregate_type},{title:'Пользователь',dataIndex:'actor_name'}]
  const tabs=useMemo(()=>[
    {key:'overview',label:'Обзор',children:<Row gutter={[16,16]}>{(model?.overview?.ap||[]).map((x,i)=><Col key={`ap-${i}`} xs={24} md={8}><Card><Statistic title={`Поставщикам · ${statusLabel[x.status]||x.status} · ${x.currency}`} value={Number(x.total_amount)}/></Card></Col>)}{(model?.overview?.ar||[]).map((x,i)=><Col key={`ar-${i}`} xs={24} md={8}><Card><Statistic title={`От клиентов · ${statusLabel[x.status]||x.status} · ${x.currency}`} value={Number(x.expected_amount)}/></Card></Col>)}</Row>},
    {key:'payables',label:'Задолженность поставщикам',children:<Table rowKey="id" size="small" dataSource={model?.ap_cases} columns={generic}/>},
    {key:'commitments',label:'Обязательства',children:<Table rowKey="id" size="small" scroll={{x:900}} dataSource={model?.commitments} columns={commitments}/>},
    {key:'invoices',label:'Счета поставщиков',children:<Table rowKey="id" size="small" dataSource={model?.invoices} columns={generic}/>},
    {key:'supplier-payments',label:'Оплаты поставщикам',children:<Table rowKey="id" size="small" dataSource={model?.supplier_payments} columns={generic}/>},
    {key:'receivables',label:'Задолженность клиентов',children:<Table rowKey="id" size="small" scroll={{x:850}} dataSource={model?.receivables} columns={receivables}/>},
    {key:'customer-payments',label:'Оплаты клиентов',children:<Table rowKey="id" size="small" dataSource={model?.customer_payments} columns={generic}/>},
    {key:'exceptions',label:'Исключения и споры',children:<><Table rowKey={r=>`${r.type}-${r.reference_id}`} size="small" dataSource={model?.overview?.exceptions} columns={[{title:'Тип',dataIndex:'type'},{title:'Основание',dataIndex:'reference'},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>}]} /><Table rowKey="id" size="small" dataSource={model?.disputes} columns={generic}/></>},
    {key:'calendar',label:'Платёжный календарь',children:<Table rowKey={r=>`${r.direction}-${r.reference_id}`} size="small" dataSource={model?.overview?.calendar} columns={[{title:'Направление',dataIndex:'direction',render:v=>v==='AP'?'Поставщику':'От клиента'},{title:'Основание',dataIndex:'reference'},{title:'Дата',dataIndex:'event_date'},{title:'Сумма',render:(_,r)=>money(r.amount,r.currency)},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>}]} />},
    {key:'forecast',label:'Прогноз',children:<Alert showIcon type="info" message="Операционный прогноз" description="Исходные валюты сохраняются. Раздел не создаёт налоговый или бухгалтерский регистр и не выполняет неявную конвертацию валют."/>},
    {key:'completion',label:'Готовность к завершению',children:<Space direction="vertical" style={{width:'100%'}}><Alert showIcon type="warning" message="Только оценка готовности" description="Финансовый раздел показывает готовность, но не закрывает договор, закупку, склад, доставку или заказ."/><Button disabled={!can('financial_operations.completion.view')} onClick={async()=>{try{setCompletion(await getCompletionReadiness())}catch(e){appMessage.error(errorText(e))}}}>Обновить готовность</Button>{completion?<Descriptions bordered size="small" column={1}><Descriptions.Item label="Расчёты с поставщиками">{completion.ap?.length||0}</Descriptions.Item><Descriptions.Item label="Расчёты с клиентами">{completion.ar?.length||0}</Descriptions.Item><Descriptions.Item label="Изменяет завершение заказа">Нет</Descriptions.Item></Descriptions>:null}</Space>},
    {key:'history',label:'История',children:<Table rowKey="id" size="small" dataSource={model?.history} columns={history}/>},
  ],[can,completion,model])
  const submit=(values)=>{if(drawer==='ap')return run(()=>materializeAp(values.source_id),'Обязательства поставщику созданы');if(drawer==='ar')return run(()=>materializeReceivable(values.source_id),'Задолженность клиента создана');if(drawer==='invoice')return run(()=>registerSupplierInvoice({...values,allocations:allocationKeys(values.allocations,'invoice')}),'Счёт поставщика зарегистрирован');if(drawer==='credit-note')return run(()=>registerCreditNote(values),'Кредит-нота зарегистрирована');if(drawer==='payment-plan')return run(()=>createPaymentPlan(values),'План оплаты создан');if(drawer==='supplier-payment')return run(()=>registerSupplierPayment({...values,allocations:allocationKeys(values.allocations,'supplier-payment')}),'Оплата поставщику зарегистрирована');if(drawer==='customer-payment')return run(()=>registerCustomerPayment({...values,allocations:allocationKeys(values.allocations,'customer-payment')}),'Оплата клиента зарегистрирована');if(drawer==='adjustment')return run(()=>registerCustomerCreditAdjustment(values),'Задолженность скорректирована');if(drawer==='dispute')return run(()=>openFinancialDispute(values),'Спор открыт')}
  return <PageWrapper title="Финансовые операции"><Space direction="vertical" size={16} style={{width:'100%'}}><Card><Space direction="vertical" style={{width:'100%'}}><Title level={3} style={{margin:0}}>Финансовые операции</Title><Text type="secondary">Обязательства перед поставщиками, счета, оплаты и расчёты с клиентами</Text><Space wrap>{can('financial_operations.ap.manage')&&<Button onClick={()=>open('ap')}>Принять подтверждение поставщика</Button>}{can('financial_operations.ar.manage')&&<Button onClick={()=>open('ar')}>Создать задолженность клиента</Button>}{can('financial_operations.ap.invoices')&&<><Button onClick={()=>open('invoice',{allocations:[{}],source_channel:'EMAIL',own_legal_entity_key:'CRUSHER_PARTS_DEFAULT'})}>Зарегистрировать счёт поставщика</Button><Button onClick={()=>open('credit-note')}>Зарегистрировать кредит-ноту</Button></>}{can('financial_operations.ap.payments')&&<><Button onClick={()=>open('payment-plan')}>Запланировать оплату поставщику</Button><Button onClick={()=>open('supplier-payment',{allocations:[{}],source_type:'BANK_STATEMENT',own_legal_entity_key:'CRUSHER_PARTS_DEFAULT'})}>Зарегистрировать оплату поставщику</Button></>}{can('financial_operations.ar.payments')&&<Button onClick={()=>open('customer-payment',{allocations:[{}],source_type:'BANK_STATEMENT'})}>Зарегистрировать оплату клиента</Button>}{can('financial_operations.adjustments')&&<Button onClick={()=>open('adjustment')}>Корректировка задолженности</Button>}{can('financial_operations.ap.disputes')&&<Button danger onClick={()=>open('dispute')}>Открыть спор</Button>}</Space></Space></Card><Card loading={loading}><Tabs items={tabs}/></Card></Space>
    <Drawer width={680} open={Boolean(drawer)} title={drawer==='ap'?'Принять подтверждение поставщика':drawer==='ar'?'Создать задолженность клиента':drawer==='invoice'?'Счёт поставщика':drawer==='supplier-payment'?'Оплата поставщику':drawer==='customer-payment'?'Оплата клиента':'Финансовая операция'} onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>form.submit()}>Сохранить</Button>}><Form form={form} layout="vertical" onFinish={submit}>
      {drawer==='ap'?<Form.Item name="source_id" label="Подтверждение поставщика" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.confirmation_intake||[]).map(item=>({value:Number(item.id),disabled:Boolean(item.case_number),label:`${item.supplier_name||'Поставщик'} · ${item.po_number} · ${item.confirmation_reference}${item.case_number?` · уже ${item.case_number}`:''}`}))}/></Form.Item>:null}
      {drawer==='ar'?<Form.Item name="source_id" label="Обязательство договора" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.commitment_intake||[]).map(item=>({value:Number(item.id),disabled:Boolean(item.receivable_number),label:`${item.client_name} · ${item.contract_number} · строка ${item.line_number} · ${money(item.line_total,item.currency)}${item.receivable_number?` · уже ${item.receivable_number}`:''}`}))}/></Form.Item>:null}
      {drawer==='invoice'?<><Alert type="info" showIcon message="Распределите счёт по обязательствам" description="Выберите понятные бизнес-объекты; внутренние номера записей вводить не требуется." style={{marginBottom:12}}/><Form.Item name="supplier_id" label="Поставщик" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={[...new Map((model?.ap_cases||[]).map(x=>[x.supplier_id,{value:x.supplier_id,label:x.supplier_name||'Поставщик'}])).values()]}/></Form.Item><Form.Item name="own_legal_entity_key" label="Наша организация" rules={[{required:true}]}><Select options={[{value:'CRUSHER_PARTS_DEFAULT',label:'Основная организация'}]}/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="external_invoice_number" label="Номер счёта" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="invoice_date" label="Дата счёта" rules={[{required:true}]}><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="contractual_due_date" label="Оплатить до"><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="currency" label="Валюта" rules={[{required:true}]}><Input maxLength={3}/></Form.Item></Col><Col span={12}><Form.Item name="gross_amount" label="Сумма счёта" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item name="source_channel" label="Канал получения" rules={[{required:true}]}><Select options={[{value:'EMAIL',label:'Электронная почта'},{value:'PORTAL',label:'Портал поставщика'},{value:'PAPER',label:'Бумажный документ'}]}/></Form.Item></Col></Row><Form.Item name="evidence_reference" label="Документ-основание" rules={[{required:true}]}><Input placeholder="Например: счёт и письмо поставщика"/></Form.Item><Form.List name="allocations">{(fields,{add,remove})=><Space direction="vertical" style={{width:'100%'}}><Text strong>Распределение по обязательствам</Text>{fields.map(({key:fieldKey,...field})=><Card key={fieldKey} size="small"><Row gutter={12}><Col span={16}><Form.Item {...field} name={[field.name,'commitment_id']} label="Обязательство" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.commitments||[]).map(x=>({value:x.id,label:`${x.case_number} · ${x.supplier_name} · ${money(x.expected_amount,x.currency)}`}))}/></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name,'amount']} label="Сумма" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col></Row>{fields.length>1?<Button danger size="small" onClick={()=>remove(field.name)}>Убрать строку</Button>:null}</Card>)}<Button onClick={()=>add()}>Добавить обязательство</Button></Space>}</Form.List></>:null}
      {drawer==='credit-note'?<><Form.Item name="supplier_id" label="Поставщик" rules={[{required:true}]}><Select options={[...new Map((model?.ap_cases||[]).map(x=>[x.supplier_id,{value:x.supplier_id,label:x.supplier_name||`Поставщик ${x.supplier_id}`}])).values()]}/></Form.Item><Form.Item name="original_supplier_invoice_id" label="Исходный счёт"><Select options={(model?.invoices||[]).map(x=>({value:x.id,label:`${x.external_invoice_number} · ${x.supplier_name}`}))}/></Form.Item>{[['external_credit_number','Номер кредит-ноты'],['credit_date','Дата'],['currency','Валюта'],['amount','Сумма'],['evidence_reference','Документ-основание']].map(([n,label])=><Form.Item key={n} name={n} label={label} rules={[{required:true}]}><Input/></Form.Item>)}</>:null}
      {drawer==='payment-plan'?<><Form.Item name="supplier_invoice_id" label="Счёт поставщика"><Select allowClear options={(model?.invoices||[]).map(x=>({value:x.id,label:`${x.external_invoice_number} · ${x.supplier_name} · ${money(x.gross_amount,x.currency)}`}))}/></Form.Item><Form.Item name="commitment_id" label="Обязательство перед поставщиком"><Select allowClear options={(model?.commitments||[]).map(x=>({value:x.id,label:`${x.case_number} · ${x.supplier_name} · ${money(x.expected_amount,x.currency)}`}))}/></Form.Item>{[['planned_payment_date','Плановая дата'],['amount','Сумма'],['currency','Валюта'],['note','Примечание']].map(([n,label])=><Form.Item key={n} name={n} label={label} rules={n==='note'?[]:[{required:true}]}><Input/></Form.Item>)}</>:null}
      {drawer==='supplier-payment'?<><Alert type="info" showIcon message="Распределите оплату по счёту и обязательству" description="Система проверит соответствие поставщика, валюты и ранее распределённого счёта." style={{marginBottom:12}}/><Form.Item name="supplier_id" label="Поставщик" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={[...new Map((model?.ap_cases||[]).map(x=>[x.supplier_id,{value:x.supplier_id,label:x.supplier_name||'Поставщик'}])).values()]}/></Form.Item><Form.Item name="own_legal_entity_key" label="Наша организация" rules={[{required:true}]}><Select options={[{value:'CRUSHER_PARTS_DEFAULT',label:'Основная организация'}]}/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="payment_number" label="Номер платежа" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="payment_date" label="Дата платежа" rules={[{required:true}]}><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="currency" label="Валюта" rules={[{required:true}]}><Input maxLength={3}/></Form.Item></Col><Col span={12}><Form.Item name="amount" label="Сумма" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col></Row><Form.Item name="bank_reference" label="Подтверждение банка" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="source_type" label="Источник" rules={[{required:true}]}><Select options={[{value:'BANK_STATEMENT',label:'Банковская выписка'},{value:'PAYMENT_ORDER',label:'Платёжное поручение'}]}/></Form.Item><Form.List name="allocations">{(fields,{add,remove})=><Space direction="vertical" style={{width:'100%'}}><Text strong>Распределение оплаты</Text>{fields.map(({key:fieldKey,...field})=><Card key={fieldKey} size="small"><Form.Item {...field} name={[field.name,'invoice_id']} label="Счёт поставщика" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.invoices||[]).map(x=>({value:x.id,label:`${x.external_invoice_number} · ${x.supplier_name} · ${money(x.gross_amount,x.currency)}`}))}/></Form.Item><Row gutter={12}><Col span={16}><Form.Item {...field} name={[field.name,'commitment_id']} label="Обязательство" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.commitments||[]).map(x=>({value:x.id,label:`${x.case_number} · ${x.supplier_name} · ${money(x.expected_amount,x.currency)}`}))}/></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name,'amount']} label="Сумма" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col></Row>{fields.length>1?<Button danger size="small" onClick={()=>remove(field.name)}>Убрать строку</Button>:null}</Card>)}<Button onClick={()=>add()}>Добавить распределение</Button></Space>}</Form.List></>:null}
      {drawer==='customer-payment'?<><Alert type="info" showIcon message="Распределите поступление по задолженности клиента" description="Выберите клиента и задолженность по номеру договора и сумме." style={{marginBottom:12}}/><Form.Item name="client_id" label="Клиент" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={[...new Map((model?.receivables||[]).map(x=>[x.client_id,{value:x.client_id,label:x.client_name||'Клиент'}])).values()]}/></Form.Item><Form.Item name="own_legal_entity_key" label="Наша организация" rules={[{required:true}]}><Select options={[...new Map((model?.receivables||[]).map(x=>[x.own_legal_entity_key,{value:x.own_legal_entity_key,label:'Организация из договора'}])).values()]}/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="payment_number" label="Номер поступления" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="payment_date" label="Дата поступления" rules={[{required:true}]}><Input type="date"/></Form.Item></Col><Col span={12}><Form.Item name="currency" label="Валюта" rules={[{required:true}]}><Input maxLength={3}/></Form.Item></Col><Col span={12}><Form.Item name="amount" label="Сумма" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col></Row><Form.Item name="bank_reference" label="Подтверждение банка" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="source_type" label="Источник" rules={[{required:true}]}><Select options={[{value:'BANK_STATEMENT',label:'Банковская выписка'},{value:'PAYMENT_ORDER',label:'Платёжное поручение'}]}/></Form.Item><Form.List name="allocations">{(fields,{add,remove})=><Space direction="vertical" style={{width:'100%'}}><Text strong>Распределение поступления</Text>{fields.map(({key:fieldKey,...field})=><Card key={fieldKey} size="small"><Row gutter={12}><Col span={16}><Form.Item {...field} name={[field.name,'receivable_id']} label="Задолженность клиента" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={(model?.receivables||[]).map(x=>({value:x.id,label:`${x.receivable_number} · ${x.client_name} · ${money(x.expected_amount,x.currency)}`}))}/></Form.Item></Col><Col span={8}><Form.Item {...field} name={[field.name,'amount']} label="Сумма" rules={[{required:true}]}><InputNumber min={0.0001} precision={4} style={{width:'100%'}}/></Form.Item></Col></Row>{fields.length>1?<Button danger size="small" onClick={()=>remove(field.name)}>Убрать строку</Button>:null}</Card>)}<Button onClick={()=>add()}>Добавить задолженность</Button></Space>}</Form.List></>:null}
      {drawer==='adjustment'?<><Form.Item name="receivable_id" label="Задолженность клиента" rules={[{required:true}]}><Select options={(model?.receivables||[]).map(x=>({value:x.id,label:`${x.receivable_number} · ${x.client_name} · ${money(x.expected_amount,x.currency)}`}))}/></Form.Item>{[['amount','Сумма'],['currency','Валюта'],['reason_code','Причина'],['approval_reference','Согласование']].map(([n,label])=><Form.Item key={n} name={n} label={label} rules={[{required:true}]}><Input/></Form.Item>)}</>:null}
      {drawer==='dispute'?<><Form.Item name="supplier_invoice_id" label="Счёт поставщика"><Select allowClear options={(model?.invoices||[]).map(x=>({value:x.id,label:`${x.external_invoice_number} · ${x.supplier_name}`}))}/></Form.Item><Form.Item name="commitment_id" label="Обязательство"><Select allowClear options={(model?.commitments||[]).map(x=>({value:x.id,label:`${x.case_number} · ${x.supplier_name}`}))}/></Form.Item>{[['disputed_amount','Оспариваемая сумма'],['currency','Валюта'],['reason_code','Причина'],['description','Описание']].map(([n,label])=><Form.Item key={n} name={n} label={label} rules={n==='description'?[]:[{required:true}]}><Input/></Form.Item>)}</>:null}
    </Form></Drawer></PageWrapper>
}
