import React,{useCallback,useEffect,useMemo,useState} from 'react'
import {Alert,Button,Card,Descriptions,Drawer,Empty,Form,Input,InputNumber,List,Select,Space,Table,Tabs,Tag,Typography} from 'antd'
import {useNavigate,useSearchParams} from 'react-router-dom'
import PageWrapper from '@/components/common/PageWrapper'
import useCapabilities from '@/hooks/useCapabilities'
import {appMessage} from '@/utils/uiFeedback'
import {acceptSupplierConfirmation,createProcurementCase,createPurchaseOrder,createPurchaseOrderRevision,generatePoCandidates,getProcurementWorkspace,issuePurchaseOrder,listProcurementCases,listProcurementCommitments,reconfirmProcurementItem,registerSupplierConfirmation,sendPurchaseOrder} from '@/features/procurementExecution/api/procurementExecutionApi'
const {Text,Title}=Typography
const err=(e)=>e?.response?.data?.error?.message||e?.response?.data?.message||e?.message||'Операция не выполнена'
const requestKey=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`
const color={READY:'green',RECONFIRMATION_REQUIRED:'orange',SOURCING_UPDATE_REQUIRED:'red',PRICING_RECHECK_REQUIRED:'magenta',BLOCKED:'red',SENT:'blue',ACCEPTED:'green',MATCHED:'cyan',DISCREPANCY:'red'}
const statusLabel={READY:'Готово',ACTIVE:'В работе',OPEN:'В работе',READY_FOR_PO:'Готово к созданию заказов',AWAITING_CONFIRMATION:'Ожидается подтверждение поставщика',CHANGE_REQUIRED:'Требуются изменения',RECONFIRMATION_REQUIRED:'Требуется подтверждение',SOURCING_UPDATE_REQUIRED:'Нужна новая закупочная проработка',PRICING_RECHECK_REQUIRED:'Нужно перепроверить цену',BLOCKED:'Заблокировано',SENT:'Отправлено',ACCEPTED:'Принято',MATCHED:'Соответствует',DISCREPANCY:'Есть расхождения',DRAFT:'Черновик',ISSUED:'Выпущено',CONVERTED:'Заказ создан',CONFIRMED:'Подтверждено поставщиком'}
const Status=({value})=><Tag color={color[value]}>{statusLabel[value]||'Неизвестное состояние'}</Tag>
export default function ProcurementExecutionWorkspacePage(){
 const {can}=useCapabilities(),[params,setParams]=useSearchParams(),navigate=useNavigate(),caseId=Number(params.get('case'))||null
 const [cases,setCases]=useState([]),[commitmentIntake,setCommitmentIntake]=useState([]),[model,setModel]=useState(null),[loading,setLoading]=useState(true),[drawer,setDrawer]=useState(null),[target,setTarget]=useState(null)
 const [createForm]=Form.useForm(),[reconfirmForm]=Form.useForm(),[poForm]=Form.useForm(),[sendForm]=Form.useForm(),[confirmationForm]=Form.useForm()
 const loadCases=useCallback(async()=>{setLoading(true);try{const [caseRows,commitmentRows]=await Promise.all([listProcurementCases(),listProcurementCommitments()]);setCases(caseRows);setCommitmentIntake(commitmentRows)}catch(e){appMessage.error(err(e))}finally{setLoading(false)}},[])
 const loadCase=useCallback(async(id)=>{if(!id){setModel(null);return}try{setModel(await getProcurementWorkspace(id))}catch(e){appMessage.error(err(e))}},[])
 useEffect(()=>{loadCases()},[loadCases]);useEffect(()=>{if(caseId)loadCase(caseId);else if(!loading&&cases.length)setParams({case:String(cases[0].id)},{replace:true})},[caseId,cases,loadCase,loading,setParams])
 const refresh=async()=>Promise.all([loadCases(),caseId?loadCase(caseId):Promise.resolve()])
 const run=async(fn,message,close=true)=>{try{const result=await fn();appMessage.success(message);if(close)setDrawer(null);await refresh();return result}catch(e){appMessage.error(err(e));return null}}
 const orders=model?.purchase_orders||[],items=model?.items||[],ready=items.filter(x=>x.readiness_status==='READY')
 const currentRevisions=useMemo(()=>orders.map(o=>o.revisions?.find(r=>Number(r.id)===Number(o.current_revision_id))||o.revisions?.at(-1)).filter(Boolean),[orders])
 const queueColumns=[{title:'Исполнение',dataIndex:'case_number',render:(v,r)=><Space direction="vertical" size={0}><Text strong>{v}</Text><Text type="secondary">{r.title}</Text></Space>},{title:'Состояние',dataIndex:'status',render:v=><Status value={v}/>},{title:'Позиций',dataIndex:'item_count'},{title:'Готово',dataIndex:'ready_count'},{title:'Заказов',dataIndex:'po_count'}]
 const itemColumns=[{title:'Поставщик',render:(_,r)=>r.supplier_snapshot_json?.name},{title:'Артикул поставщика',render:(_,r)=>r.supplier_part_snapshot_json?.part_number||'—'},{title:'Закупка',render:(_,r)=>`${r.purchase_quantity} ${r.uom}`},{title:'Цена',render:(_,r)=>`${r.purchase_unit_price} ${r.purchase_currency}`},{title:'Готовность',dataIndex:'readiness_status',render:v=><Status value={v}/>},{title:'Причины',render:(_,r)=>(r.readiness_reasons_json||[]).length?'Требуется уточнение данных':'—'},{title:'',render:(_,r)=>can('procurement_execution.reconfirm')?<Button size="small" onClick={()=>{setTarget(r);reconfirmForm.setFieldsValue({supplier_id:r.supplier_id,supplier_part_number:r.supplier_part_snapshot_json?.part_number,purchase_quantity:Number(r.purchase_quantity),moq:Number(r.moq),pack_quantity:Number(r.pack_quantity),uom:r.uom,purchase_unit_price:Number(r.purchase_unit_price),purchase_currency:r.purchase_currency,payment_terms:r.payment_terms,incoterms:r.incoterms,available:'yes'});setDrawer('reconfirm')}}>Подтвердить</Button>:null}]
 const tabs=model?[
  {key:'readiness',label:`Готовность (${items.length})`,children:<><Alert type="info" showIcon message="Исполняются только обязательства действующего договора" description="Единица измерения и закупочные параметры берутся из неизменяемого решения закупочной проработки; исходные документы доступны только для чтения." style={{marginBottom:12}}/><Table rowKey="id" size="small" pagination={false} dataSource={items} columns={itemColumns}/></>},
  {key:'commitments',label:'Обязательства договора',children:<List bordered dataSource={items} renderItem={i=><List.Item><List.Item.Meta title={i.supplier_part_snapshot_json?.part_number||'Позиция поставщика'} description={`${i.supplier_snapshot_json?.name||'Поставщик'} · ${i.purchase_quantity} ${i.uom} · ${i.purchase_unit_price} ${i.purchase_currency}`}/></List.Item>}/>},
  {key:'trace',label:'Связь с закупочной проработкой',children:<List bordered dataSource={items} renderItem={i=><List.Item><List.Item.Meta title={`${i.supplier_snapshot_json?.name||'Поставщик'} · ${i.supplier_part_snapshot_json?.part_number||'позиция'}`} description="Источник подтверждён: договор → расчёт цены → решение закупочной проработки"/></List.Item>}/>},
  {key:'reconfirmations',label:'Подтверждения параметров',children:<List bordered dataSource={items.flatMap(i=>i.reconfirmations||[])} locale={{emptyText:'Подтверждения отсутствуют'}} renderItem={r=><List.Item><List.Item.Meta title={<Status value={r.status}/>} description={`${r.evidence_reference} · ${r.confirmed_at?new Date(r.confirmed_at).toLocaleString('ru-RU'):'—'}`}/></List.Item>}/>},
  {key:'candidates',label:`Кандидаты заказов (${model.candidates?.length||0})`,children:<Space direction="vertical" style={{width:'100%'}}>{can('procurement_purchase_orders.manage')?<Button type="primary" disabled={!ready.length} onClick={()=>run(()=>generatePoCandidates(caseId),'Кандидаты заказов сформированы',false)}>Сформировать из готовых позиций</Button>:null}<List bordered dataSource={model.candidates||[]} renderItem={c=>{const related=items.filter(item=>(c.item_ids||[]).map(Number).includes(Number(item.id)));return <List.Item actions={c.status==='READY'&&can('procurement_purchase_orders.manage')?[<Button key="po" onClick={()=>{setTarget(c);poForm.setFieldsValue({legal_basis_type:'PURCHASE_ORDER_AS_CONTRACT'});setDrawer('po')}}>Создать заказ</Button>]:[]}><List.Item.Meta title={<Space><Text strong>{related[0]?.supplier_snapshot_json?.name||'Поставщик'}</Text><Status value={c.status}/></Space>} description={`${related.length} поз. · ${related.map(item=>item.supplier_part_snapshot_json?.part_number).filter(Boolean).join(', ')}`}/></List.Item>}}/></Space>},
  {key:'po',label:`Заказы поставщикам (${currentRevisions.length})`,children:<List bordered dataSource={orders} locale={{emptyText:'Заказы поставщикам отсутствуют'}} renderItem={o=>{const r=o.revisions?.find(x=>Number(x.id)===Number(o.current_revision_id))||o.revisions?.at(-1);const actions=r?.status==='DRAFT'&&can('procurement_purchase_orders.issue')?[<Button key="issue" onClick={()=>run(()=>issuePurchaseOrder(r.id),`Заказ ${o.po_number} выпущен`,false)}>Выпустить</Button>]:r?.status==='ISSUED'&&can('procurement_purchase_orders.issue')?[<Button key="send" onClick={()=>{setTarget(r);sendForm.resetFields();sendForm.setFieldsValue({channel:'MANUAL'});setDrawer('send')}}>Отправить</Button>]:r?.status==='SENT'&&can('procurement_purchase_orders.manage')?[<Button key="revision" onClick={()=>run(()=>createPurchaseOrderRevision(o.id,{comments:'Новая версия представления'}),`Новая версия заказа ${o.po_number} создана`,false)}>Создать версию {Number(r.revision_number)+1}</Button>]:[];return <List.Item actions={actions}><List.Item.Meta title={<Space><Text strong>{o.po_number}</Text><Status value={o.status}/></Space>} description={`Версия ${r?.revision_number||'—'} · юридическое основание ${r?.legal_basis_status==='READY'?'подтверждено':'требует проверки'} · после выпуска неизменяемо`}/></List.Item>}}/>},
  {key:'confirmations',label:'Подтверждения заказов',children:<Space direction="vertical" style={{width:'100%'}}>{currentRevisions.filter(r=>r.status==='SENT').map(r=>{const order=orders.find(o=>Number(o.id)===Number(r.procurement_purchase_order_id));return <Button key={r.id} onClick={()=>{setTarget(r);confirmationForm.resetFields();confirmationForm.setFieldsValue({lines:(r.lines||[]).map(line=>({line_number:line.line_number,supplier_part_number:line.supplier_part_snapshot_json?.part_number,quantity:Number(line.quantity),uom:line.uom,unit_price:Number(line.unit_price),currency:line.currency,available:true}))});setDrawer('confirmation')}}>Зарегистрировать подтверждение {order?.po_number||'заказа'}</Button>})}<List bordered dataSource={currentRevisions.flatMap(r=>r.confirmations||[])} locale={{emptyText:'Подтверждения отсутствуют'}} renderItem={c=><List.Item actions={c.status==='MATCHED'&&can('procurement_purchase_orders.confirmations.accept')?[<Button key="accept" type="primary" onClick={()=>run(()=>acceptSupplierConfirmation(c.id),'Подтверждение поставщика принято',false)}>Принять</Button>]:[]}><List.Item.Meta title={<Space><Text>{c.confirmation_reference}</Text><Status value={c.status}/></Space>} description="Принятие подтверждения не создаёт складские, платёжные или бухгалтерские документы."/></List.Item>}/></Space>},
  {key:'changes',label:`Запросы на изменение (${model.change_requests?.length||0})`,children:<List bordered dataSource={model.change_requests||[]} locale={{emptyText:'Запросы на изменение отсутствуют'}} renderItem={c=><List.Item actions={c.target_domain==='SOURCING'&&c.sourcing_case_id?[<Button key="source" type="link" onClick={()=>navigate(`/sourcing?case=${c.sourcing_case_id}`)}>Открыть исходную закупочную проработку</Button>]:[]}><List.Item.Meta title={`${c.target_domain==='SOURCING'?'Требуется пересмотр закупочной проработки':'Требуется перепроверка цены'}`} description="Создан отслеживаемый запрос на изменение; исходное решение не изменено."/></List.Item>}/>},
  {key:'history',label:'История',children:<List bordered dataSource={model.history||[]} renderItem={e=><List.Item><List.Item.Meta title={String(e.event_type||'Событие').replaceAll('_',' ').toLowerCase()} description={`${e.created_at?new Date(e.created_at).toLocaleString('ru-RU'):'—'} · ${e.actor_name||'Система'}`}/></List.Item>}/>},
 ]:[]
 return <PageWrapper title="Исполнение закупки"><Space direction="vertical" size={16} style={{width:'100%'}}><Card><Space style={{width:'100%',justifyContent:'space-between'}}><div><Title level={3} style={{margin:0}}>Исполнение закупки</Title><Text type="secondary">Обязательства договора → подтверждение поставщика → заказ поставщику → подтверждение заказа</Text></div>{can('procurement_execution.manage')?<Button type="primary" onClick={()=>setDrawer('create')}>Принять обязательства</Button>:null}</Space></Card><Card title="Очередь исполнения" styles={{body:{padding:0}}}><Table rowKey="id" loading={loading} size="small" dataSource={cases} columns={queueColumns} onRow={r=>({onClick:()=>setParams({case:String(r.id)}),style:{cursor:'pointer'}})}/></Card>{model?<Card title={<Space><Text strong>{model.procurement_case.case_number}</Text><Status value={model.procurement_case.status}/></Space>}><Tabs items={tabs}/></Card>:<Empty description="Выберите исполнение закупки"/>}</Space>
 <Drawer open={drawer==='create'} title="Обязательства действующего договора" width={620} onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>createForm.submit()}>Создать</Button>}><Form form={createForm} layout="vertical" onFinish={async v=>{const result=await run(()=>createProcurementCase({title:v.title,contract_commitment_ids:v.commitment_ids,request_key:requestKey('procurement-case')}),'Исполнение закупки создано');if(result?.case_id)setParams({case:String(result.case_id)})}}><Form.Item name="title" label="Название"><Input/></Form.Item><Form.Item name="commitment_ids" label="Обязательства договора" rules={[{required:true}]}><Select mode="multiple" showSearch optionFilterProp="label" options={commitmentIntake.map(item=>({value:Number(item.id),disabled:Boolean(item.procurement_item_id),label:`${item.client_name} · ${item.contract_number} · строка ${item.line_number} · ${item.client_representation_snapshot_json?.description||'позиция'} · ${item.quantity} ${item.uom}${item.procurement_item_id?' · уже принято':''}`}))}/></Form.Item></Form></Drawer>
 <Drawer open={drawer==='reconfirm'} title="Подтверждение поставщика" onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>reconfirmForm.submit()}>Сохранить</Button>}><Form form={reconfirmForm} layout="vertical" onFinish={v=>run(()=>reconfirmProcurementItem(target.id,{evidence_reference:v.evidence_reference,confirmed:{...v,available:v.available==='yes'}}),'Подтверждение зафиксировано')}><Alert type="info" showIcon message={target?.supplier_snapshot_json?.name||'Выбранный поставщик'} description="Подтвердите коммерческие параметры поставщика. Внутренние идентификаторы не требуются." style={{marginBottom:12}}/><Form.Item name="supplier_id" hidden><InputNumber/></Form.Item><Form.Item name="evidence_reference" label="Ссылка на подтверждение" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="available" label="Доступность"><Select options={[{value:'yes',label:'Доступно'},{value:'no',label:'Недоступно'}]}/></Form.Item>{[['purchase_quantity','Закупаемое количество'],['moq','Минимальный заказ (MOQ)'],['pack_quantity','Количество в упаковке'],['purchase_unit_price','Цена за единицу']].map(([name,label])=><Form.Item key={name} name={name} label={label}><InputNumber style={{width:'100%'}}/></Form.Item>)}{[['supplier_part_number','Артикул поставщика'],['uom','Единица измерения'],['purchase_currency','Валюта закупки'],['payment_terms','Условия оплаты'],['incoterms','Incoterms']].map(([name,label])=><Form.Item key={name} name={name} label={label}><Input/></Form.Item>)}</Form></Drawer>
 <Drawer open={drawer==='po'} title="Заказ поставщику" onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>poForm.submit()}>Создать</Button>}><Form form={poForm} layout="vertical" onFinish={v=>run(()=>createPurchaseOrder(target.id,v),'Черновик заказа поставщику создан')}><Alert type="info" showIcon message="Срок оплаты фиксируется в заказе" description="Финансовые обязательства будут созданы из принятого подтверждения поставщика без интерпретации свободного текста." style={{marginBottom:12}}/><Form.Item name="legal_basis_type" label="Юридическое основание" rules={[{required:true}]}><Select options={[{value:'PURCHASE_ORDER_AS_CONTRACT',label:'Заказ как самостоятельный договор'},{value:'SUPPLIER_AGREEMENT',label:'Действующий договор с поставщиком'}]}/></Form.Item><Form.Item name="payment_due_date" label="Оплатить поставщику до" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name="policy_reference" label="Основание применения заказа-договора"><Input/></Form.Item><Form.Item name="approval_reference" label="Ссылка на согласование"><Input/></Form.Item><Form.Item name="agreement_reference" label="Договор с поставщиком"><Input/></Form.Item><Form.Item name="valid_through" label="Договор действует до"><Input type="date"/></Form.Item><Form.Item name="supplier_contact" label="Контакт поставщика"><Input/></Form.Item><Form.Item name="delivery_contact" label="Контакт по доставке"><Input/></Form.Item><Form.Item name="comments" label="Комментарий"><Input.TextArea/></Form.Item></Form></Drawer>
 <Drawer open={drawer==='send'} title="Отправка заказа поставщику" onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>sendForm.submit()}>Зафиксировать отправку</Button>}><Form form={sendForm} layout="vertical" onFinish={v=>run(()=>sendPurchaseOrder(target.id,{...v,recipients:String(v.recipients).split(',').map(x=>x.trim()).filter(Boolean)}),'Точная копия отправки сохранена')}><Form.Item name="recipients" label="Получатели" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="channel" label="Канал"><Select options={[{value:'MANUAL',label:'Вручную'},{value:'EMAIL',label:'Электронная почта'},{value:'PORTAL',label:'Портал поставщика'}]}/></Form.Item><Form.Item name="evidence_reference" label="Подтверждение отправки" rules={[{required:true}]}><Input/></Form.Item></Form></Drawer>
 <Drawer open={drawer==='confirmation'} title="Подтверждение заказа поставщиком" width={720} onClose={()=>setDrawer(null)} extra={<Button type="primary" onClick={()=>confirmationForm.submit()}>Сравнить с заказом</Button>}><Form form={confirmationForm} layout="vertical" onFinish={v=>run(()=>registerSupplierConfirmation(target.id,{confirmation_reference:v.confirmation_reference,evidence_reference:v.evidence_reference,lines:v.lines}),'Подтверждение поставщика зарегистрировано')}><Alert type="info" showIcon message="Подтвердите параметры из ответа поставщика" description="Значения заказа уже подставлены. Изменяйте только те поля, где поставщик прислал другие условия." style={{marginBottom:12}}/><Form.Item name="confirmation_reference" label="Номер подтверждения поставщика" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="evidence_reference" label="Подтверждающий документ или письмо" rules={[{required:true}]}><Input/></Form.Item><Form.List name="lines">{fields=><Space direction="vertical" style={{width:'100%'}}>{fields.map(({key,...field},index)=><Card key={key} size="small" title={`Позиция ${index+1}`}><Form.Item {...field} name={[field.name,'line_number']} hidden><InputNumber/></Form.Item><Form.Item {...field} name={[field.name,'available']} hidden><Input/></Form.Item><Form.Item {...field} name={[field.name,'supplier_part_number']} label="Артикул поставщика"><Input/></Form.Item><Space wrap align="start"><Form.Item {...field} name={[field.name,'quantity']} label="Количество"><InputNumber min={0} style={{width:140}}/></Form.Item><Form.Item {...field} name={[field.name,'uom']} label="Единица"><Input style={{width:100}}/></Form.Item><Form.Item {...field} name={[field.name,'unit_price']} label="Цена за единицу"><InputNumber min={0} style={{width:160}}/></Form.Item><Form.Item {...field} name={[field.name,'currency']} label="Валюта"><Input maxLength={3} style={{width:100}}/></Form.Item></Space></Card>)}</Space>}</Form.List></Form></Drawer>
 </PageWrapper>
}
