import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { App, Button, Card, Col, Empty, Form, Input, InputNumber, Modal, Row, Select, Space, Statistic, Table, Tabs, Tag, Typography } from 'antd'
import { InboxOutlined, ReloadOutlined, SafetyCertificateOutlined } from '@ant-design/icons'
import axios from '@/api/axiosInstance'
import useCapabilities from '@/hooks/useCapabilities'

const { Text, Title } = Typography
const qty = (value) => Number(value || 0).toLocaleString('ru-RU', { maximumFractionDigits: 3 })
const statusColor = { OPEN:'blue',PARTIALLY_RECEIVED:'gold',RECEIVED:'green',BLOCKED:'red',ACTIVE:'green',RELEASED:'default',HOLD:'orange',REJECTED:'red' }
const statusLabel = { OPEN:'Открыто',PARTIALLY_RECEIVED:'Принято частично',RECEIVED:'Принято',BLOCKED:'Заблокировано',ACTIVE:'Активно',RELEASED:'Разрешено',HOLD:'На удержании',REJECTED:'Отклонено' }

export default function WarehouseInventoryWorkspacePage(){
  const { message }=App.useApp(),{can}=useCapabilities(),[data,setData]=useState({stats:{},inbound:[],stock:[],reservations:[],counts:[]}),[locations,setLocations]=useState({warehouses:[],places:[]}),[loading,setLoading]=useState(false),[confirmation,setConfirmation]=useState(''),[receipt,setReceipt]=useState(null),[receiptLines,setReceiptLines]=useState([]),[receiptForm]=Form.useForm()
  const load=useCallback(async()=>{setLoading(true);try{const [overview,master]=await Promise.all([axios.get('/warehouse-inventory/overview'),axios.get('/warehouse-inventory/locations')]);setData(overview.data||{});setLocations(master.data||{})}catch(error){message.error(error?.response?.data?.message||'Не удалось загрузить складские данные')}finally{setLoading(false)}},[message])
  useEffect(()=>{load()},[load])
  const materialize=async()=>{if(!confirmation)return;try{const {data:result}=await axios.post(`/warehouse-inventory/inbound/from-accepted-confirmations/${confirmation}`);message.success(result.already_exists?'Ожидаемое поступление уже существует':'Ожидаемое поступление создано');setConfirmation('');load()}catch(error){message.error(error?.response?.data?.message||'Не удалось создать ожидаемое поступление')}}
  const reconcile=async(row)=>{try{const {data:result}=await axios.post(`/warehouse-inventory/inbound/${row.id}/reconcile`);if(result.status==='OPEN')message.success('Сведения сопоставлены, приёмка разблокирована');else message.warning('Не все обязательные сведения удалось сопоставить');load()}catch(error){message.error(error?.response?.data?.message||'Не удалось повторить сопоставление')}}
  const openReceipt=async(row)=>{try{const {data:details}=await axios.get(`/warehouse-inventory/inbound/${row.id}`),lines=(details.lines||[]).filter(line=>Number(line.remaining_quantity)>0&&line.status!=='BLOCKED');setReceiptLines(lines);setReceipt(row);receiptForm.setFieldsValue({received_at:new Date().toISOString(),idempotency_key:`receipt-${row.id}-${Date.now()}`,lines:[{expectation_line_id:lines[0]?.id||null,received_quantity:Number(lines[0]?.remaining_quantity||1),damaged_quantity:0,missing_quantity:0}]})}catch(error){message.error(error?.response?.data?.message||'Не удалось открыть expected inbound')}}
  const submitReceipt=async()=>{try{const values=await receiptForm.validateFields();await axios.post(`/warehouse-inventory/inbound/${receipt.id}/receipts`,values);message.success('Факт приёмки проведён');setReceipt(null);receiptForm.resetFields();load()}catch(error){if(error?.errorFields)return;message.error(error?.response?.data?.message||'Приёмка не проведена')}}
  const stockColumns=useMemo(()=>[
    {title:'Единица запаса',dataIndex:'stock_unit_code',render:(value,row)=><Space direction="vertical" size={0}><Text strong>{value}</Text><Text type="secondary">{row.internal_lot_number}</Text></Space>},
    {title:'Позиция каталога',render:(_,row)=><Space direction="vertical" size={0}><Text>{row.manufacturer_part_number||'Без артикула'}</Text><Text type="secondary">{row.display_name}</Text></Space>},
    {title:'Деталь поставщика',render:(_,row)=><Space direction="vertical" size={0}><Text>{row.supplier_part_number||'Без артикула'}</Text><Text type="secondary">{row.supplier_name}</Text></Space>},
    {title:'Место',render:(_,row)=><span>{row.warehouse_name}{row.storage_place_code?` / ${row.storage_place_code}`:''}</span>},
    {title:'Качество',dataIndex:'quality_status',render:value=><Tag color={statusColor[value]}>{statusLabel[value]||'Неизвестно'}</Tag>},
    {title:'Физически',dataIndex:'physical_quantity',align:'right',render:qty},{title:'Удержано',dataIndex:'held_quantity',align:'right',render:qty},{title:'В резерве',dataIndex:'reserved_quantity',align:'right',render:qty},{title:'Доступно',dataIndex:'available_quantity',align:'right',render:value=><Text strong>{qty(value)}</Text>},
  ],[])
  const inboundColumns=[{title:'Ожидаемое поступление',render:(_,row)=><Text strong>{row.expectation_number}</Text>},{title:'Состояние',dataIndex:'status',render:value=><Tag color={statusColor[value]}>{statusLabel[value]||'Неизвестно'}</Tag>},{title:'Позиций',dataIndex:'line_count',align:'right'},{title:'Ожидается',dataIndex:'expected_quantity',align:'right',render:qty},{title:'Принято',dataIndex:'received_quantity',align:'right',render:qty},{title:'Действие',render:(_,row)=>can('warehouse_inventory.receiving')&&['OPEN','PARTIALLY_RECEIVED'].includes(row.status)?<Button size="small" onClick={()=>openReceipt(row)}>Принять</Button>:can('warehouse_inventory.inbound.manage')&&row.status==='BLOCKED'?<Button size="small" onClick={()=>reconcile(row)}>Повторить сопоставление</Button>:null}]
  const reservationColumns=[{title:'Резерв',dataIndex:'reservation_number'},{title:'Основание',render:(_,row)=>row.source_reference||'Заказ клиента'},{title:'Состояние',dataIndex:'status',render:value=><Tag color={statusColor[value]}>{statusLabel[value]||'Неизвестно'}</Tag>},{title:'Распределений',dataIndex:'allocation_count',align:'right'},{title:'Зарезервировано',dataIndex:'reserved_quantity',align:'right',render:qty}]
  return <Space direction="vertical" size="large" style={{width:'100%'}}>
    <Row justify="space-between" align="middle"><Col><Title level={3} style={{margin:0}}>Склад</Title><Text type="secondary">Ожидаемые поступления, приёмка, остатки, качество и резервирование</Text></Col><Col><Button icon={<ReloadOutlined/>} loading={loading} onClick={load}>Обновить</Button></Col></Row>
    <Row gutter={16}>{[['Физический остаток','physical_quantity'],['На удержании','held_quantity'],['Зарезервировано','reserved_quantity'],['Доступно','available_quantity']].map(([title,key])=><Col xs={12} lg={6} key={key}><Card><Statistic title={title} value={Number(data.stats?.[key]||0)} precision={3}/></Card></Col>)}</Row>
    <Tabs items={[
      {key:'inbound',label:'Поступления и приёмка',children:<Space direction="vertical" style={{width:'100%'}}>{can('warehouse_inventory.inbound.manage')&&<Card size="small" title="Создать ожидаемое поступление из подтверждения поставщика"><Space><Select value={confirmation||undefined} onChange={setConfirmation} placeholder="Выберите подтверждение поставщика" style={{width:520}} options={(data.confirmation_intake||[]).map(item=>({value:String(item.id),disabled:Boolean(item.expectation_number),label:`${item.supplier_name||'Поставщик'} · ${item.po_number} · ${item.confirmation_reference}${item.expectation_number?` · уже ${item.expectation_number}`:''}`}))}/><Button type="primary" icon={<InboxOutlined/>} onClick={materialize}>Создать</Button></Space><div><Text type="secondary">Ожидание не увеличивает физический остаток. Неполные сведения о позиции блокируют приёмку.</Text></div></Card>}<Table rowKey="id" loading={loading} columns={inboundColumns} dataSource={data.inbound||[]} locale={{emptyText:<Empty description="Ожидаемые поступления отсутствуют"/>}}/></Space>},
      {key:'stock',label:'Остатки и доступность',children:<Table rowKey="stock_unit_id" loading={loading} columns={stockColumns} dataSource={data.stock||[]} locale={{emptyText:<Empty description="Складские остатки пока отсутствуют"/>}}/>},
      {key:'reservations',label:'Резервы',children:<Table rowKey="id" loading={loading} columns={reservationColumns} dataSource={data.reservations||[]}/>},
      {key:'counts',label:'Инвентаризации',children:<Card><Space><SafetyCertificateOutlined/><Text>Слепая инвентаризация и подтверждённые корректировки доступны пользователям с соответствующим правом.</Text></Space></Card>},
      {key:'boundaries',label:'Правила раздела',children:<Card><Space direction="vertical"><Text>Справочник позиций и эквивалентность доступны только для чтения.</Text><Text>Данные деталей поставщика не изменяются со склада.</Text><Text>Подтверждение поставщика и заказ доступны только для чтения.</Text></Space></Card>},
    ]}/>
    <Modal title={`Фактическая приёмка · ${receipt?.expectation_number||''}`} open={Boolean(receipt)} onCancel={()=>setReceipt(null)} onOk={submitReceipt} okText="Провести приёмку" width={760}>
      <Form form={receiptForm} layout="vertical"><Row gutter={12}><Col span={12}><Form.Item name="warehouse_id" label="Физический склад" rules={[{required:true}]}><Select options={(locations.warehouses||[]).map(x=>({value:x.id,label:x.name}))}/></Form.Item></Col><Col span={12}><Form.Item name="receiving_place_id" label="Место приёмки"><Select allowClear options={(locations.places||[]).map(x=>({value:x.id,label:x.code}))}/></Form.Item></Col></Row><Form.Item name="received_at" label="Дата и время приёмки" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="evidence_reference" label="Документ-основание" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="idempotency_key" hidden><Input/></Form.Item><Form.List name="lines">{fields=><Space direction="vertical" style={{width:'100%'}}>{fields.map(field=><Card key={field.key} size="small"><Row gutter={8}><Col span={7}><Form.Item {...field} name={[field.name,'expectation_line_id']} label="Ожидаемая позиция" rules={[{required:true}]}><Select options={receiptLines.map(line=>({value:line.id,label:`${line.line_number}. ${line.manufacturer_part_number||line.supplier_part_number||'Позиция'} · ${qty(line.remaining_quantity)} ${line.uom}`}))}/></Form.Item></Col><Col span={6}><Form.Item {...field} name={[field.name,'received_quantity']} label="Принято" rules={[{required:true}]}><InputNumber min={0.001} step={1} style={{width:'100%'}}/></Form.Item></Col><Col span={5}><Form.Item {...field} name={[field.name,'damaged_quantity']} label="Повреждено"><InputNumber min={0} style={{width:'100%'}}/></Form.Item></Col><Col span={6}><Form.Item {...field} name={[field.name,'supplier_lot_number']} label="Партия поставщика"><Input/></Form.Item></Col></Row></Card>)}</Space>}</Form.List></Form>
    </Modal>
  </Space>
}
