import axios from "@/api/axiosInstance"

export const listPricingCases = (params = {}) => axios.get("/pricing/cases", { params }).then(({ data }) => data)
export const getPricingWorkspace = (caseId) => axios.get(`/pricing/cases/${caseId}`).then(({ data }) => data)
export const listPricingRouteTemplates = () => axios.get("/pricing/route-templates").then(({ data }) => data)
export const listPricingSourcingDecisions = () => axios.get("/pricing/intake/sourcing-decisions").then(({ data }) => data)
export const createPricingCase = (payload) => axios.post("/pricing/cases/from-sourcing-decision", payload).then(({ data }) => data)
export const fixPricingInput = (caseId) => axios.post(`/pricing/cases/${caseId}/fix-input`).then(({ data }) => data)
export const createCalculationGroup = (caseId, payload) => axios.post(`/pricing/cases/${caseId}/groups`, payload).then(({ data }) => data)
export const createRouteVariant = (groupId, payload) => axios.post(`/pricing/groups/${groupId}/variants`, payload).then(({ data }) => data)
export const reviseRouteVariantParameters = (variantId, payload) => axios.post(`/pricing/variants/${variantId}/parameters`, payload).then(({ data }) => data)
export const calculateRouteVariant = (variantId) => axios.post(`/pricing/variants/${variantId}/calculate`).then(({ data }) => data)
export const selectRouteVariant = (variantId) => axios.post(`/pricing/variants/${variantId}/select`).then(({ data }) => data)
export const approveClientPrices = (caseId, payload = {}) => axios.post(`/pricing/cases/${caseId}/client-prices/approve`, payload).then(({ data }) => data)
export const requestPriceOverride = (priceLineId, payload) => axios.post(`/pricing/client-price-lines/${priceLineId}/override-requests`, payload).then(({ data }) => data)
export const reviewPriceOverride = (overrideId, payload) => axios.post(`/pricing/price-overrides/${overrideId}/review`, payload).then(({ data }) => data)
export const finalizePricingDecision = (caseId, payload = {}) => axios.post(`/pricing/cases/${caseId}/decisions/finalize`, payload).then(({ data }) => data)
export const requestSourcingRework = (caseId, payload) => axios.post(`/pricing/cases/${caseId}/rework-signals`, payload).then(({ data }) => data)
export const revealPricingSupplierIdentity = (inputLineId) => axios.get(`/pricing/input-lines/${inputLineId}/supplier-identity`).then(({ data }) => data)
