import axios from '@/api/axiosInstance'
export const listProcurementCases=(params={})=>axios.get('/procurement-execution/cases',{params}).then(({data})=>data)
export const listProcurementCommitments=()=>axios.get('/procurement-execution/contract-commitments').then(({data})=>data)
export const getProcurementWorkspace=(id)=>axios.get(`/procurement-execution/cases/${id}`).then(({data})=>data)
export const createProcurementCase=(payload)=>axios.post('/procurement-execution/cases/from-contract-commitments',payload).then(({data})=>data)
export const reconfirmProcurementItem=(id,payload)=>axios.post(`/procurement-execution/items/${id}/reconfirmations`,payload).then(({data})=>data)
export const generatePoCandidates=(id)=>axios.post(`/procurement-execution/cases/${id}/po-candidates`).then(({data})=>data)
export const createPurchaseOrder=(id,payload)=>axios.post(`/procurement-execution/po-candidates/${id}/purchase-orders`,payload).then(({data})=>data)
export const createPurchaseOrderRevision=(id,payload={})=>axios.post(`/procurement-execution/purchase-orders/${id}/revisions`,payload).then(({data})=>data)
export const updatePurchaseOrderDraft=(id,payload)=>axios.patch(`/procurement-execution/po-revisions/${id}`,payload).then(({data})=>data)
export const issuePurchaseOrder=(id,payload={})=>axios.post(`/procurement-execution/po-revisions/${id}/issue`,payload).then(({data})=>data)
export const sendPurchaseOrder=(id,payload)=>axios.post(`/procurement-execution/po-revisions/${id}/send`,payload).then(({data})=>data)
export const registerSupplierConfirmation=(id,payload)=>axios.post(`/procurement-execution/po-revisions/${id}/confirmations`,payload).then(({data})=>data)
export const acceptSupplierConfirmation=(id)=>axios.post(`/procurement-execution/confirmations/${id}/accept`).then(({data})=>data)
